	db.restaurants.find()
	db.restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.find({},{_id:0,restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.findOne({},{"_id":0,"restaurant_id":1,"name":1,"borough":1,"address.zipcode":1})
	db.restaurants.find({"borough":"Bronx"})
	db.restaurants.find({"borough":"Bronx"}).limit(5)
	db.restaurants.find({"borough":"Bronx"}).skip(5).limit(5)	
	db.restaurants.find({"grades.score":{$gt:90}})
	db.restaurants.find({"grades.score":{$gt:80,$lt:100}})
	 db.restaurants.find({"address.coord.0":{$gt:-95.754168}})
	db.restaurants.find({$and: [{"grades.score":{$gt:70}},{"address.coord.1":{$lt:-65.754168}}]})
	db.restaurants.find({"cuisine":{$not:{$eq:"American "}},"grades.score":{$gt:70},"address.coord.0":{$lt:-65.754168}})
	db.restaurants.find({$and: [{"cuisine":{$not:{$eq:"American"}}},{"grades.grade":{$eq:"A"}},{"borough":{$not:{$eq:"Brooklyn"}}}]})
	db.restaurants.find({"name":/^wil/},{restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.find({"name":/ces$/},{restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.find({"name":/reg/},{restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.find({$and: [{"borough":{$eq:"Bronx"}},{"cuisine":{$in:["American ", "Chinese"]}}]})
	db.restaurants.find({borough: {$in:["Staten Island","Queens","Bronx","Brooklyn"]}},{restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.find({borough:{$nin:["Staten Island","Queens","Bronx","Brooklyn"]}},{restaurant_id:1,name:1,borough:1,cuisine:1})
	db.restaurants.find({"grades.score":{$not:{$gte:10}}},{restaurant_id:1,name:1,borough:1,cuisine:1})
	
